services:
  api:
    volumes:
      - ./backend:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONDONTWRITEBYTECODE=1

  beat:
    volumes:
      - ./backend:/app

  worker:
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
